name: Test installation instructions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install:
    name: install on (os=${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-24.04-arm", "ubuntu-latest","macos-latest"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.9
      - name: conda setup
        shell: bash -el {0}
        run: |
          conda create -n bitnet-cpp python=3.9
          conda activate bitnet-cpp
      - name: setup env
        run: |
          pip install -r requirements.txt
          huggingface-cli download microsoft/BitNet-b1.58-2B-4T-gguf --local-dir models/BitNet-b1.58-2B-4T
          python setup_env.py -md models/BitNet-b1.58-2B-4T -q i2_s
      
      - name: run
        run: python run_inference.py -m models/BitNet-b1.58-2B-4T/ggml-model-i2_s.gguf -p "you are a helpful assistant. what is the sun?"
